OT116-72
alkemyTech/OT116-CLIENT pull request #3
Opened 2021-12-17 02:43 UTC by jmsanchezdiaz

# Resumen

Subo la tarea del ticket OT116-72, esta era estructurar el componente responsive *Header* de la campaña escolar al cual renombre ***CampaignHeader***. El componente fue diseñando para ser reutilizado en la otra landing de las campañas.

### Observaciones:

- Tuve un error que no me permitia commitear debido al nombre del archivo *pre-commit.sh* este mismo lo renombre *pre--commit.sh* y ahi pude (Esta es la unica solución que encontre).

# Evidencia:

## Video:
https://user-images.githubusercontent.com/73983475/146480149-2b3298b5-5459-47c3-9747-505b44cc26d4.mp4

## Imagen:

![Evidencia_Header_Alkemy_First_Frame](https://user-images.githubusercontent.com/73983475/146480210-6226db03-4e89-4733-92ad-3d6a7fd6d200.png)

2021-12-17 15:02 UTC, valessol approved these changes

2021-12-17 19:42 UTC, betofiorani approved these changes

2021-12-20 16:56 UTC, dvelezroman requested changes
Bien el componente.... buen PR.. 

lo unico que el nombre del pre-commit no se debe cambiar porque ya no lo estaria tomando... esa no seria la solucion para poder commitear...

2021-12-20 18:50 UTC, jmsanchezdiaz commented
> Bien el componente.... buen PR..
> 
> lo unico que el nombre del pre-commit no se debe cambiar porque ya no lo estaria tomando... esa no seria la solucion para poder commitear...

|

2021-12-20 19:50 UTC, dvelezroman approved these changes

2021-12-20 21:31 UTC, merged