[WIP] OT116-116 Screen List of Activities
alkemyTech/OT116-CLIENT pull request #48
Opened 2022-01-12 01:05 UTC by GonzaloVolonterio

Criterios de aceptación: Al ingresar a la ruta /activities, mostrará el listado de Testimonios. Obtendrá los datos del endpoint de listado, en el caso de que aún no esté listo, los obtendrá desde un array que representarán los datos. en Cards.

Al realizar la coneccion hacia el servicio me genera el error de webpack que se puede ver en el video, como mencione el meet de hoy.

https://www.loom.com/share/3c54a93e1e3747ddac70e73b82f8e3f0

2022-01-12 17:29 UTC, jmsanchezdiaz commented on src/Components/Activies/ActiviesList.jsx
> +    dispatch(getAllActivities()).catch(() => {
Creo que el dispatch no deja usar el catch. Tambien el nombre de la action es getActivities y tenes que importarlo con {} porque * as getAllActivities estas importando todo el archivo como getAllActivities, y de esta forma tendrias que acceder asi getAllActivities.getActivities()

2022-01-12 17:30 UTC, jmsanchezdiaz commented on src/Components/Activies/ActiviesList.jsx
> +  const { activities } = useSelector((state) => state);
ahi te estas trayendo el estado de actividades para acceder a la lista seria activities.activities o podes hacer asi `const { activities } = useSelector((state) => state.activities);`

2022-01-12 17:32 UTC, jmsanchezdiaz commented on src/Components/Activies/ActiviesList.jsx
> +import * as getAllActivities from '../../app/activitiesReducer/activitiesActions';
a lo que me refiero mas a abajo seria que el import para usar las funciones por si solas seria asi.
`import { getActivities } from '../../app/activitiesReducer/activitiesActions'; `
Sino si queres hacerlo de otra manera podria ser asi.
`import * as activitiesActions from '../../app/activitiesReducer/activitiesActions`
y usar la asi `dispatch(activitiesActions.getActivities());`

2022-01-12 20:42 UTC, dvelezroman requested changes
cambiar segun comentarios

2022-01-14 16:13 UTC, GonzaloVolonterio commented on src/Components/Activies/ActiviesList.jsx
> +    dispatch(getAllActivities()).catch(() => {
funciono d10 gracias.

2022-01-14 16:41 UTC, jmsanchezdiaz approved these changes
Genial gonza!

2022-01-14 19:31 UTC, dvelezroman approved these changes

2022-01-14 19:38 UTC, merged