OT116-107 - Activities Search Form - With Testing and Documentation
alkemyTech/OT116-CLIENT pull request #50
Opened 2022-01-12 02:15 UTC by jmsanchezdiaz

# Summary 
Hola, en realidad este ticket no estaba en el SPRINT activo pero decidi realizarlo para poder incorporar testing a mis habilidades aparte de que nos permita avanzar con el proyecto.
Ahora si, en el ticket ***OT116-107*** se me pedia realizar un formulario de busquedad de actividades al endpoint ***activitities?search***.
## Requerimientos
- Si el valor del input es menor a 3 caracteres, se realiza una peticion get al endpoint *activities*.
- Si el valor del input es mayor a 3 caracteres, se realiza una peticion get al endpoint *activities* con la query *search*.

## Observations
- Tambien realice una pequeña refactorizacion del servicio de actividades y agrege el metodo para buscar actividad por titulo.
- En sí, el ticket 107 no tenia otro ticket de testing, pero decidi crearlo para poder agregarlo a mis habilidades.
- Entiendo completamente si no quieren aceptar este PR, ya que no figuraba en el SPRINT activo.

# Evidence
### Funcionamiento
https://user-images.githubusercontent.com/73983475/149051170-1fe55521-ea0f-413a-84b5-e2b1eca74baa.mp4

### Testing (con Jest y React Testing Library)

https://user-images.githubusercontent.com/73983475/149051207-95e97f37-ef25-4e28-95a7-8217734b154f.mp4

2022-01-12 20:37 UTC, dvelezroman commented on src/Components/ActivitiesSearch/ActivitiesSearch.jsx
> +  }, 500);
anadir : 
```
... 500, {
leading: true
trailing: false,
} 
```

2022-01-12 20:38 UTC, dvelezroman requested changes
probar con params en debounce

2022-01-14 19:31 UTC, dvelezroman approved these changes

2022-01-14 20:10 UTC, betofiorani approved these changes
genio!

2022-01-14 20:44 UTC, merged